version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_SECRET_NAME=mongodb_uri
      - AWS_REGION=us-east-1
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: always
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: secureapp
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
